"""empty message

Revision ID: 701a4dd59955
Revises: 
Create Date: 2023-01-10 15:32:22.951172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701a4dd59955'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(length=80),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
