"""empty message

Revision ID: 994d39240d48
Revises: b146fdb01edf
Create Date: 2023-01-19 13:24:19.628747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994d39240d48'
down_revision = 'b146fdb01edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), nullable=False),
    sa.Column('_password', sa.BLOB(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=120), server_default=sa.text("('')"), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=120), server_default=sa.text("('')"), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
